### ISSUE TITLE
As a user, I want to be able to view comments and ratings of food and meals provided by other users. 

### ISSUE THREAD

**Issue by lucys-s** [agiledev-students-fall2023/4-final-project-agile-architects-1#29]
## Estimation of effort (optional)

- User Interface: 2. Designing UI should be a little complex but still manageable. Backend: 4. The process of retrieving comments and ratings from the backend can be complex. User Experience: 4. User Experience is crucial for our web app, and we need to ensure everything flows smoothly. Testing: 3. We need to ensure that the code is error-free and works the way we demand.

## Acceptance criteria (optional)

- Show comments and ratings. 
- Click to see detailed comments and any replies. 
- Click to see rating distribution from 1 to 5 stars.

**Comment by Gong2047** [comment]
This is not a separate user story and it should be put under the other user stories
